%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/shivasenthilkumar/Desktop/Copy of Mean.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 06-Oct-2022 10:22:23

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 8);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "B2:I16";

% Specify column names and types
opts.VariableNames = ["Sam", "Cade", "Jay", "Jennifer", "Min", "Sensitive", "Confidence", "sex"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "categorical", "double", "categorical"];

% Specify variable properties
opts = setvaropts(opts, ["Sensitive", "sex"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("/Users/shivasenthilkumar/Desktop/Copy of Mean.xlsx", opts, "UseExcel", false);

%% Convert to output type
Sam = tbl.Sam;
Cade = tbl.Cade;
Jay = tbl.Jay;
Jennifer = tbl.Jennifer;
Min = tbl.Min;
Sensitive = tbl.Sensitive;
Confidence = tbl.Confidence;
sex = tbl.sex;

%% Clear temporary variables
clear opts tbl

T = table(Sam, Cade, Jay, Jennifer, Min, Sensitive, Confidence);
LM = fitglm(T, 'Confidence~Sam+Cade+Jay+Jennifer+Min')
