%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/shivasenthilkumar/Desktop/Friedman Test.xlsx
%    Worksheet: Friedman Test
%
% Auto-generated by MATLAB on 21-Sep-2022 11:53:28

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = "Friedman Test";
opts.DataRange = "A2:C32";

% Specify column names and types
opts.VariableNames = ["VarName1", "typhoonLagoon", "Summer"];
opts.VariableTypes = ["double", "categorical", "categorical"];

% Specify variable properties
opts = setvaropts(opts, ["typhoonLagoon", "Summer"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("/Users/shivasenthilkumar/Desktop/Friedman Test.xlsx", opts, "UseExcel", false);

%% Convert to output type
VarName1 = tbl.VarName1;
typhoonLagoon = tbl.typhoonLagoon;
Summer = tbl.Summer;

%% Clear temporary variables
clear opts tbl
[p,tt,stats] = anovan(income,{attraction,season},'varnames',{'attraction', 'season'});
